# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Peter Stefek
email: pstefek@oberlin.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a third year student at Oberlin College. I am currently majoring in Math and Computer Science. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  mr4k

background-image: url('social_graph.png')

# Build settings
markdown: kramdown
